#!/usr/bin/ruby
# Teste de fidelidade discordiano 0.2.3 (sem loop mortal)
# por rev. Beraldo

puts "Amigo, olá. Pode me dizer qual teu nome?"
nome = gets.chomp.split(" ").map {|i| i.capitalize}.join(" ")

if (nome == "Não" or nome == "Nao" )
	puts "Então vá se f***r!"
else 
	puts "Seja bem-vindo a este Fascinante Teste de Fidelidade Discordiano, #{nome}.\n"
	puts "Me diga, então: qual teu número preferido?"
	numero = gets.chomp.to_i
	if (numero == 23 or numero == 5)
		puts "Por Éris!, você é um discordiano de fato!"
	else
		puts "Não... Esqueça que viu este programa."
	end
end