#!/bin/bash
s=$((3600*$(printf %d $(date +%H))+60*$(printf %d $(date +%M))+$(printf %d $(date +%S))))
printf "%02d:%02d:%02d\n" $((s/8640)) $((((1000*s/864)%10000)/100)) $((((1000*s/864)%10000)%100))
